#!/bin/bash
mogrify -resize 968x648 /home/pi/scripts/photobooth/*.jpg
montage /home/pi/scripts/photobooth/*.jpg -tile 2x2 -geometry +10+10 /home/pi/scripts/photobooth/temp_montage2.jpg
montage /home/pi/scripts/photobooth/temp_montage2.jpg /home/pi/scripts/photobooth/photobooth_label.jpg -tile 2x1 -geometry +5+5 /home/pi/scripts/photobooth/temp_montage3.jpg
suffix=$(date +%H%M%S)
cp /home/pi/scripts/photobooth/temp_montage3.jpg /home/pi/scripts/photobooth/PB_archive/PB_${suffix}.jpg
